// Writes the dish-by-dish comparison of the three factor tables (spec 2026-10-08-combined-emission-factors-design.md §6).
// Run: node seed/compare-factors.ts > docs/factor-comparison.md
import { COMBINED, OWID_ONLY, SG_ONLY } from "./factors.ts";
import { ITEMS } from "./data.ts";
import { bandOf, computeKg } from "../src/worker/lib/carbon.ts";

const combined = Object.fromEntries(Object.entries(COMBINED).map(([k, v]) => [k, v.kg]));
const tables = { owid_only: OWID_ONLY, sg_only: SG_ONLY, combined };
const fmt = (n: number | null) => (n == null ? "n/a" : n.toFixed(2));
const lines: string[] = [
  "# Menu under each emission-factor table",
  "",
  "Generated by `node seed/compare-factors.ts`. Bands: green ≤ 0.7 kg, amber ≤ 1.4 kg, red above (comparison only; app scoring is unchanged).",
  "",
  "- **owid_only:** Poore & Nemecek (2018) via OWID totals, including land-use change.",
  "- **sg_only:** Ecosperity (2019) Singapore values, which exclude land-use change; OWID for tofu, milk, coffee, sugar.",
  "- **combined (official):** Ecosperity + OWID's land-use-change stage; OWID where Ecosperity has no value.",
  "",
  "Ingredient grams are portion assumptions; rice and noodles are dry weight. Meat and vegetable grams have no recorded raw/cooked basis.",
  "",
  "| Dish | kg OWID | band | kg SG | band | kg combined | band | band changed (OWID → combined)? |",
  "|---|---|---|---|---|---|---|---|",
];
const sums: Record<string, number[]> = { owid_only: [], sg_only: [], combined: [] };
for (const i of ITEMS) {
  const kg = Object.fromEntries(Object.entries(tables).map(([n, t]) => [n, computeKg(i.parts, t)])) as Record<string, number | null>;
  if (i.kind === "meal") for (const n of Object.keys(sums)) if (kg[n] != null) sums[n].push(kg[n]!);
  const b = (n: string) => (i.kind === "meal" ? bandOf(kg[n]) ?? "n/a" : "drink");
  const changed = i.kind === "meal" && b("owid_only") !== b("combined") ? `yes (${b("owid_only")} → ${b("combined")})` : "no";
  lines.push(`| ${i.name} | ${fmt(kg.owid_only)} | ${b("owid_only")} | ${fmt(kg.sg_only)} | ${b("sg_only")} | ${fmt(kg.combined)} | ${b("combined")} | ${changed} |`);
}
const avg = (a: number[]) => (a.reduce((x, y) => x + y, 0) / a.length).toFixed(2);
lines.push("", "**Menu average (meals):** " + Object.entries(sums).map(([n, a]) => `${n} ${avg(a)} kg`).join(" · "), "");
lines.push(
  "**Boundary caveat:** owid_only includes land-use change; sg_only does not. combined adds only OWID's land-use stage to the Singapore values (packaging and losses are already inside Ecosperity's boundary; retail is excluded throughout). The land-use stage is a global average, while Singapore's real sourcing differs.",
  "",
);
process.stdout.write(lines.join("\n"));
